In [17]:
import numpy as np
import pandas as pd
import statistics

In [18]:
data = [4, 8, 15, 21, 21, 24, 25, 28, 34]
print(data)

[4, 8, 15, 21, 21, 24, 25, 28, 34]


In [19]:
size = 3
def freq(data, size):
    n = len(data)//size
    for i in range(size):
        chunk = data[i*n : (i+1)*n]
        print(chunk)

freq(data, size)

[4, 8, 15]
[21, 21, 24]
[25, 28, 34]


In [20]:
bin1 = np.zeros((3, 3,))
bin2 = np.zeros((3, 3,))
bin3 = np.zeros((3, 3,))

In [21]:
# Bin Mean

for i in range(0, 9, 3):
    k = i//3
    mean = (data[i] + data[i+1] + data[i+2])/3
    for i in range(3):
        bin1[k,j] = mean

print(bin1)

[[ 0.  0.  9.]
 [ 0.  0. 22.]
 [ 0.  0. 29.]]


In [22]:
# Bin Median

for i in range(0, 9, 3):
    k = i//3
    for i in range(3):
        bin2[k,j] = data[i+1]

print(bin2)

[[ 0.  0. 21.]
 [ 0.  0. 21.]
 [ 0.  0. 21.]]


In [23]:
# Bin Boundary

for i in range(0, 9, 3):
    k = i//3
    bin3[k] = (data[i], data[i], data[i+2])

print(bin3)

[[ 4.  4. 15.]
 [21. 21. 24.]
 [25. 25. 34.]]
