In [20]:
# Binning Data
import pandas as pd
import numpy as np
import statistics

# data = np.array([13, 15, 35, 11, 10, 5, 72, 55, 50, 215, 204, 92])
# data = np.sort(data)

d = pd.read_csv("sales_price.csv")
print(d)

    sales
0      13
1      15
2      35
3      11
4      10
5       5
6      72
7      55
8      50
9     215
10    204
11     92


In [22]:
p = d['sales']
print(p)

t = []
for i in p:
    t.append(i)
    t.sort()
print(t)


0      13
1      15
2      35
3      11
4      10
5       5
6      72
7      55
8      50
9     215
10    204
11     92
Name: sales, dtype: int64
[5, 10, 11, 13, 15, 35, 50, 55, 72, 92, 204, 215]


In [25]:
binSize = 3

def equiFreq(arr, binSize):
    arrlen = len(arr1)
    n = int(arrlen/binSize)
    
    for i in range(0, binSize):
        arr=[]
        for j in range(i * n, (i+1) * n):
            if(j >= arrlen):
                break
            arr = arr + [arr1[j]]
        print(arr)

print("Equal Frequency Binning")
equiFreq(t, binSize)

Equal Frequency Binning
[5, 10, 11, 13]
[15, 35, 50, 55]
[72, 92, 204, 215]


In [35]:
# Bin Mean

# np.zeros(no.of partition, no.of value per part)

bin1 = np.zeros((3, 4)) 
bin2 = np.zeros((3, 4))
bin3 = np.zeros((3, 4))

# (0, no.of data, no.of value per part)
for i in range(0, 12, 4):
    k = int(i/4) # 4 = no.of value per part
    mean = (t[i] + t[i+1] + t[i+2] + t[i+3])/4
    for j in range(4):
        bin1[k, j] = mean
print("Bin Mean: \n", bin1)
        
    
    
    

Bin Mean: 
 [[  9.75   9.75   9.75   9.75]
 [ 38.75  38.75  38.75  38.75]
 [145.75 145.75 145.75 145.75]]


In [ ]:
# Bin Median

for i in range(0, 12, 4):
    k = int(i/3)
    for j in range(4):
        bin3[k, j] = t

In [37]:
for i in range(0, 12, 4):
    k = int(i/4)
    for j in range(4):
        if(t[i+j] - t[i]) < (t[i+2] - t[i+j]):
            bin2[k, j] = t[i]
        else:
            bin2[k, j] = t[i+2]

print("Bin Boundary: \n", bin2)

Bin Boundary: 
 [[  5.  11.  11.  11.]
 [ 15.  50.  50.  50.]
 [ 72.  72. 204. 204.]]
