In [14]:
# Binning Data
import pandas as pd
import numpy as np
import statistics

data = pd.read_csv("sales_price.csv")
data = data['sales'].tolist()
data.sort()
print(data)

[5, 10, 11, 13, 15, 35, 50, 55, 72, 92, 204, 215]


In [15]:
size = 3
def equiFreq(data, size):
    n = len(data)//size
    
    for i in range(size):
        chunk = data[i*n : (i+1)*n]
        print(chunk)

print("Equal Frequency Binning")
equiFreq(data, size)

Equal Frequency Binning
[5, 10, 11, 13]
[15, 35, 50, 55]
[72, 92, 204, 215]


In [16]:
bin1 = np.zeros((3, 4)) 
bin2 = np.zeros((3, 4))
bin3 = np.zeros((3, 4))

In [17]:
# Bin Mean

# (0, no.of data, no.of value per part)
for i in range(0, 12, 4):
    k = i//4 # 4 = no.of value per par
    mean = (data[i] + data[i+1] + data[i+2] + data[i+3])/4
    for j in range(4):
        bin1[k, j] = mean
print("Bin Mean: \n", bin1)

Bin Mean: 
 [[  9.75   9.75   9.75   9.75]
 [ 38.75  38.75  38.75  38.75]
 [145.75 145.75 145.75 145.75]]


In [18]:
# Bin Median

for i in range(0, 12, 4):
    k = i//4
    for j in range(4):
        bin2[k,j] = data[i+1]
print("Bin Meadian: \n",bin2)

Bin Meadian: 
 [[10. 10. 10. 10.]
 [35. 35. 35. 35.]
 [92. 92. 92. 92.]]


In [32]:
# Bin Boundary

for i in range(0, 12, 4):
    k = int(i/4)
    for j in range(4):
        if(data[i+j] - data[i]) < (data[i+2] - data[i+j]):
            bin2[k, j] = data[i]
        else:
            bin2[k, j] = data[i+2]

print("Bin Boundary: \n", bin2)

Bin Boundary: 
 [[13.  5.  5.  5.]
 [55. 15. 15. 15.]
 [72. 72. 72. 72.]]


In [33]:
# Bin Boundary (alternative)

for i in range(0, 12, 4):
    k = i//4    
    bin2[k] = [data[i], data[i], data[i], data[i+3]]
    
print("Bin Boundary: \n", bin2)

Bin Boundary: 
 [[  5.   5.   5.  13.]
 [ 15.  15.  15.  55.]
 [ 72.  72.  72. 215.]]
